### ISSUE TITLE
UnhandledPromiseRejectionWarning Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by dataexcess** [ryntab/Directus-Mailer#1]
Hello, I cloned the code and build the index.js file and put it in the correct folder. When restarting Directus it states that the Mailer extension is loaded. BUT I get this error when I try to use it:

```
(node:2933868) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
1|xxx  |     at /directus/extensions/endpoints/Mailer/index.js:1:713
1|xxx  |     at /directus/extensions/endpoints/Mailer/index.js:1:1042
1|xxx  |     at Layer.handle [as handle_request] (/directus/node_modules/express/lib/router/layer.js:95:5)
1|xxx  |     at next (/directus/node_modules/express/lib/router/route.js:144:13)
1|xxx  |     at Route.dispatch (/directus/node_modules/express/lib/router/route.js:114:3)
1|xxx  |     at Layer.handle [as handle_request] (/directus/node_modules/express/lib/router/layer.js:95:5)
1|xxx  |     at /directus/node_modules/express/lib/router/index.js:284:15
1|xxx  |     at Function.process_params (/directus/node_modules/express/lib/router/index.js:346:12)
1|xxx  |     at next (/directus/node_modules/express/lib/router/index.js:280:10)
1|xxx  |     at Function.handle (/directus/node_modules/express/lib/router/index.js:175:3)
1|xxx  | (node:2933868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
1|xxx  | (node:2933868) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any ideas?
Thnx!

**Comment by dataexcess** [comment]
I am using directus@latest.

**Comment by ryntab** [comment]
@dataexcess  Not passing a file array in the email POST body caused this error. Thanks for pointing out this bug!  You can swap in the updated files, and everything should work.

Sorry for the late reply. 😊
