### ISSUE TITLE
AWS

### ISSUE THREAD

**Issue by staminna** [ryntab/Directus-Mailer#4]
Hi

Is it compatible with AWS?
On another note, will it work with Docker Install out of the box?

Thanks for input!

**Comment by ryntab** [comment]
Hello! This extension works with the built in Directus mailer service. So, any service or configuration option mentioned here is compatible: https://docs.directus.io/self-hosted/config-options.html#email

I myself use the AWS SES configuration.

This should work with a Docker install, if you run into any problems I'll do my best to help 😊

**Comment by staminna** [comment]
Hello ryntab,
I cannot get this to work.

```
 [21:49:59] WARN (88 on 9f9fd3f13b90): [email] Error: Sendmail exited with code 1
database             |     err: {
database             |       "type": "Error",
database             |       "message": "Sendmail exited with code 1",
database             |       "stack":
database             |           Error: Sendmail exited with code 1
database             |               at ChildProcess.<anonymous> (/directus/node_modules/nodemailer/lib/sendmail-transport/index.js:142:27)
database             |               at Object.onceWrapper (node:events:628:26)
database             |               at ChildProcess.emit (node:events:513:28)
database             |               at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
database             |     }
database             | [21:49:59] POST /auth/password/request 204 81ms
```

**Comment by ryntab** [comment]
@staminna Is your Nodemailer process working with Directus outside of this extension?

**Comment by staminna** [comment]
I am not sure.
How can I find out?

**Comment by ryntab** [comment]
You should first configure the mailer in your .env file
https://docs.directus.io/self-hosted/config-options.html#email

You can test to see if it is working by inviting a user and using an email that you have access to. If you get the email, you know that Nodemailer is working.

**Comment by staminna** [comment]
Dear @ryntab 

Thank you for your quick reply!

The credentials are made up in this case, just so you know I have them right.
I am an IAM user

```
      EMAIL_VERIFY_SETUP: true
      EMAIL_FROM: "stamina@gmail.com"
      EMAIL_TRANSPORT: "SES"
      EMAIL_SES_CREDENTIALS__ACCESS_KEY_ID: ABCD1ENQ2W3C22435QPFZ
      EMAIL_SES_CREDENTIALS__SECRET_ACCESS_KEY: "+WABCD1ENQ2W3C22435QPFZ"
      EMAIL_SES_REGION: "eu-west-3"
      EMAIL_ALLOW_GUEST_SEND: false
```


`{
  "message": "Sendmail exited with code 1",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}`

The node.js error is the same as above

**Comment by ryntab** [comment]
@staminna Are you getting the same error when trying to send an email through the Directus application? For example, when trying to invite a user.

**Comment by staminna** [comment]
@ryntab Yes, exactly. And I see the Mailer extension being loaded when I set docker-compose up.

**Comment by ryntab** [comment]
I will try to replicate this, are you using the most recent version of Directus?

**Comment by staminna** [comment]
@ryntab Thanks. Yep, updated yesterday. 

I am using Docker Hub, so it shouldn't be anything on the environment.

EDIT: I had the environment settings inside the wrong docker-compose.yml section ( the database) and also in Sandbox mode. I asked to switch AWS SES into production mode and I will let you know as soon as this is done and clean up the logs. Thanks!

I was able to get a reset email for Administrator ( default user 1) but if I try to invite:


[INTERNAL_SERVER_ERROR] Email address is not verified. The following identities failed the check in region EU-WEST-3: sxxxxxxxxxa@hotmail.com

```
database             | [00:35:26] GET /users?limit=25&fields[]=first_name&fields[]=last_name&fields[]=email&fields[]=password&fields[]=avatar&fields[]=location&fields[]=title&fields[]=description&fields[]=tags&fields[]=preferences_divider&fields[]=language&fields[]=theme&fields[]=tfa_secret&fields[]=email_notifications&fields[]=admin_divider&fields[]=status&fields[]=role&fields[]=token&fields[]=id&fields[]=last_page&fields[]=last_access&fields[]=provider&fields[]=external_identifier&fields[]=auth_data&sort=email&aggregate[count][0]=* 200 10ms
database             | [00:35:26] PATCH /users/me/track/page 204 19ms
database             | [00:35:26] GET /users?limit=25&fields[]=id&fields[]=avatar.modified_on&fields[]=avatar.type&fields[]=avatar.filename_disk&fields[]=avatar.storage&fields[]=avatar.id&fields[]=first_name&fields[]=last_name&fields[]=email&sort[]=email&page=1&meta[]=filter_count&meta[]=total_count 200 15ms
database             | [00:35:27] GET /roles 200 7ms
database             | [00:35:35] ERROR (88 on 5f52024cff5c): Email address is not verified. The following identities failed the check in region EU-WEST-3: sxxxxxxxxa@hotmail.com
database             |     err: {
database             |       "type": "MessageRejected",
database             |       "message": "Email address is not verified. The following identities failed the check in region EU-WEST-3: sxxxxxxxa@hotmail.com",
database             |       "stack":
database             |           MessageRejected: Email address is not verified. The following identities failed the check in region EU-WEST-3: sxxxxxxxa@hotmail.com
database             |               at deserializeAws_queryMessageRejectedResponse (/directus/node_modules/@aws-sdk/client-ses/dist-cjs/protocols/Aws_query.js:3559:23)
database             |               at deserializeAws_querySendRawEmailCommandError (/directus/node_modules/@aws-sdk/client-ses/dist-cjs/protocols/Aws_query.js:2606:25)
database             |               at processTicksAndRejections (node:internal/process/task_queues:96:5)
database             |               at async /directus/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
database             |               at async /directus/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:13:20
database             |               at async StandardRetryStrategy.retry (/directus/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
database             |               at async /directus/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
database             |       "name": "MessageRejected",
database             |       "$fault": "client",
database             |       "$metadata": {
database             |         "httpStatusCode": 400,
database             |         "requestId": "02af97b1-3850-45ed-8e48-f13629252dea",
database             |         "attempts": 1,
database             |         "totalRetryDelay": 0
database             |       },
database             |       "Error": {
database             |         "Type": "Sender",
database             |         "Code": "MessageRejected",
database             |         "Message": "Email address is not verified. The following identities failed the check in region EU-WEST-3: sxxxxxxa@hotmail.com",
database             |         "message": "Email address is not verified. The following identities failed the check in region EU-WEST-3: sxxxxxxxa@hotmail.com"
database             |       },
database             |       "RequestId": "02af97b1-3850-45ed-8e48-f13629252dea",
database             |       "xmlns": "http://ses.amazonaws.com/doc/2010-12-01/"
database             |     }
database             | [00:35:35] POST /users/invite 500 338ms
```

**Comment by staminna** [comment]
I am still not sure if it is supposed to work only in production and domain, or can I use a sandbox with @gmail for tests?

**Comment by ryntab** [comment]
> I am still not sure if it is supposed to work only in production and domain, or can I use a sandbox with @gmail for tests?

This is unrelated to the extension and Directus. Using AWS SES in sandbox mode only allows you to send emails to verified addresses. You'll need to get production access for your SES before you can send emails.

https://docs.aws.amazon.com/ses/latest/dg/verify-addresses-and-domains.html
